#include "maps.h"

extern const MapModule MAP_GREENHILL, MAP_MAJINFOREST, MAP_ANGELISLAND, MAP_TORTURECAVE, MAP_DARKTOWER, MAP_ACT9, MAP_NASTYPARADISE, MAP_PRICELESSFREEDOM, MAP_VOLCANOVALLEY, MAP_HIDEANDSEEK2, MAP_RAVINEMIST, MAP_DOTDOTDOT, MAP_DESERTTOWN, MAP_HAUNTDREAM, MAP_WEEDZONE, MAP_MARIJUNA, MAP_FARTZONE, MAP_YOUCANTRUN, MAP_LIMPCITY, MAP_NOTPERFECT, MAP_KINDANDFAIR;

// Level modules. Add each new level here.
static const MapModule *const MODULES[] = {
    &MAP_GREENHILL,
    &MAP_MAJINFOREST,
    &MAP_ANGELISLAND,
    &MAP_TORTURECAVE,
    &MAP_DARKTOWER,
    &MAP_ACT9,
    &MAP_NASTYPARADISE,
    &MAP_PRICELESSFREEDOM,
    &MAP_VOLCANOVALLEY,
    &MAP_HIDEANDSEEK2,
    &MAP_RAVINEMIST,
    &MAP_DOTDOTDOT,
    &MAP_DESERTTOWN,
    &MAP_HAUNTDREAM,
    &MAP_WEEDZONE,
    &MAP_MARIJUNA,
    &MAP_FARTZONE,
    &MAP_YOUCANTRUN,
    &MAP_LIMPCITY,
    &MAP_NOTPERFECT,
    &MAP_KINDANDFAIR,
};

const MapModule *maps_module_for(int room)
{
    for (unsigned i = 0; i < sizeof MODULES / sizeof MODULES[0]; i++)
        if (MODULES[i] && MODULES[i]->room == room) return MODULES[i];
    return NULL;
}
