"""Export GML data tables to source/gen/anims.h.

global.player_anims / player_eanims (survivors, normal and demonized) and
global.player_exesanims (EXEs): state -> sprite, used for puppets and the local player.
"""
import os
import re

from gmproject import GM_ROOT, PORT_ROOT, c_ident, write_if_changed

KEYS = {"CHARACTER_TAILS": 1, "CHARACTER_KNUX": 2, "CHARACTER_EGGMAN": 3, "CHARACTER_AMY": 4,
        "CHARACTER_CREAM": 5, "CHARACTER_SALLY": 6,
        "EXE_ORIGINAL": 0, "EXE_CHAOS": 1, "EXE_EXETIOR": 2, "EXE_EXELLER": 3}


def parse(path, table):
    src = open(path, encoding="utf-8-sig").read()
    out = {}
    pat = re.compile(r"global\." + table + r"\[\?\s*(\w+)\]\s*=\s*\[(.*?)\];", re.S)
    for m in pat.finditer(src):
        body = re.sub(r"//[^\n]*", "", m.group(2))
        out[KEYS[m.group(1)]] = [x.strip() for x in body.split(",") if x.strip()]
    return out


def emit(name, table, rows, lines):
    width = max(len(v) for v in table.values())
    lines.append(f"#define {name}_LEN {width}")
    lines.append(f"static const s16 {name}[{rows}][{width}] = {{")
    for i in range(rows):
        sprites = table.get(i, [])
        vals = [f"SPR_{c_ident(s)[4:]}" if s.startswith("spr_") else "-1" for s in sprites]
        vals += ["-1"] * (width - len(vals))
        lines.append("    { " + ", ".join(vals) + " },")
    lines.append("};")
    counts = ", ".join(str(len(table.get(i, []))) for i in range(rows))
    lines.append(f"static const u8 {name}_COUNT[{rows}] = {{ {counts} }};")
    lines.append("")


def main():
    surv = os.path.join(GM_ROOT, "scripts", "scr_survivors", "scr_survivors.gml")
    exe = os.path.join(GM_ROOT, "scripts", "scr_exe", "scr_exe.gml")
    lines = ["// Generated by tools/export_tables.py - do not edit.", "#pragma once", "",
             '#include "sprites.h"', ""]
    emit("ANIMS_SURVIVOR", parse(surv, "player_anims"), 7, lines)
    emit("ANIMS_DEMON", parse(surv, "player_eanims"), 7, lines)
    emit("ANIMS_EXE", parse(exe, "player_exesanims"), 4, lines)
    write_if_changed(os.path.join(PORT_ROOT, "source", "gen", "anims.h"), "\n".join(lines))
    print("anims.h written")


if __name__ == "__main__":
    main()
