"""Convert the GameMaker sounds for the 3DS.

  romfs/audio/music/<name>.ogg   streamed tracks (mus_* and anything longer than 15 s):
                                 Ogg Vorbis, 32 kHz stereo, decoded with tremor at runtime
  romfs/audio/sfx/<name>.pcm     effects: "PCM1", u32 sample rate, u32 sample count, then
                                 signed 16-bit mono samples (22050 Hz)
  source/gen/sounds.h            SND_* ids, per-sound flags/volume, and NET_SNDS (the
                                 global.net_snds table used by CLIENT_SOUND_EMIT)

Needs ffmpeg; run it inside the tools image (see tools/docker/Dockerfile):
  docker build -t sonic3ds-tools tools/docker
  docker run --rm -v "<sonic3ds>:/port" -v "<disaster2d-oss-main>:/gm" -e GM_PROJECT=/gm \
      -w /port sonic3ds-tools python3 tools/export_audio.py
Outputs are only rebuilt when the source file is newer.
"""
import os
import re
import struct
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gmproject import GM_ROOT, PORT_ROOT, c_ident, iter_resources, write_if_changed  # noqa: E402

MUSIC_RATE = 32000
SFX_RATE = 22050
STREAM_MIN_SECONDS = 15.0


def newer(src, dst):
    return not os.path.exists(dst) or os.path.getmtime(src) > os.path.getmtime(dst)


def convert_music(src, dst):
    subprocess.run(["ffmpeg", "-v", "error", "-y", "-i", src, "-ac", "2", "-ar", str(MUSIC_RATE),
                    "-c:a", "libvorbis", "-q:a", "1", dst], check=True)


def convert_sfx(src, dst):
    pcm = subprocess.run(["ffmpeg", "-v", "error", "-i", src, "-ac", "1", "-ar", str(SFX_RATE),
                          "-f", "s16le", "-"], check=True, capture_output=True).stdout
    with open(dst, "wb") as f:
        f.write(b"PCM1" + struct.pack("<II", SFX_RATE, len(pcm) // 2) + pcm)


def net_sounds():
    path = os.path.join(GM_ROOT, "scripts", "net_sounds", "net_sounds.gml")
    src = open(path, encoding="utf-8-sig").read()
    body = src[src.index("global.net_snds"):]
    body = body[body.index("[") + 1:body.index("]")]
    body = re.sub(r"//[^\n]*", "", body)
    return [x.strip() for x in body.split(",") if x.strip()]


def main():
    sounds = iter_resources("sounds")
    music_dir = os.path.join(PORT_ROOT, "romfs", "audio", "music")
    sfx_dir = os.path.join(PORT_ROOT, "romfs", "audio", "sfx")
    os.makedirs(music_dir, exist_ok=True)
    os.makedirs(sfx_dir, exist_ok=True)

    rows = []
    converted = 0
    for i, (name, folder, d) in enumerate(sounds):
        src = os.path.join(folder, d.get("soundFile", ""))
        if not d.get("soundFile") or not os.path.exists(src):
            print(f"  {name}: missing sound file", file=sys.stderr)
            rows.append((name, 0, 0.0, 0.0))
            continue
        stream = name.startswith("mus_") or float(d.get("duration", 0)) > STREAM_MIN_SECONDS
        dst = os.path.join(music_dir if stream else sfx_dir, name + (".ogg" if stream else ".pcm"))
        if newer(src, dst):
            (convert_music if stream else convert_sfx)(src, dst)
            converted += 1
        rows.append((name, 2 if stream else 1, float(d.get("volume", 1.0)), float(d.get("duration", 0))))

    ids = {r[0]: i for i, r in enumerate(rows)}
    lines = ["// Generated by tools/export_audio.py - do not edit.", "#pragma once", ""]
    lines += [f"#define SND_{c_ident(n)[4:] if n.startswith('snd_') else c_ident(n)} {i}"
              for i, (n, _, _, _) in enumerate(rows)]
    lines += [f"#define SND_COUNT {len(rows)}", "",
              "// kind: 0 missing, 1 effect (romfs:/audio/sfx/<name>.pcm), 2 music (romfs:/audio/music/<name>.ogg)",
              "typedef struct { const char *name; unsigned char kind; float volume, duration; } SoundDef;",
              "static const SoundDef SOUND_DEFS[SND_COUNT] = {"]
    lines += [f'    {{ "{n}", {k}, {v:.3f}f, {t:.3f}f }},' for n, k, v, t in rows]
    lines += ["};", ""]
    net = net_sounds()
    lines += ["// global.net_snds: CLIENT_SOUND_EMIT sends an index into this table",
              f"#define NET_SNDS_COUNT {len(net)}",
              "static const short NET_SNDS[NET_SNDS_COUNT] = {"]
    lines += [f"    {ids.get(n, -1)},  // {n}" for n in net]
    lines += ["};", ""]
    write_if_changed(os.path.join(PORT_ROOT, "source", "gen", "sounds.h"), "\n".join(lines))
    print(f"{len(rows)} sounds ({sum(1 for r in rows if r[1] == 2)} music), {converted} converted")


if __name__ == "__main__":
    main()
