"""Rasterize the Sonic 3 & Knuckles HUD font (tools/fonts/s3k_hud, CC BY-SA 3.0, by chriswal1200
on FontStruct) into a pixel-exact glyph atlas for the UI text.

The font is built from square bricks; at 32 px a brick is 2x2 pixels, so rendering at 32 px
without antialiasing and keeping every second pixel gives the font at one pixel per brick.

Writes gfx/ui_font.png + .t3s (converted into romfs by the Makefile) and source/gen/ui_font.h.
"""
import os

from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT = os.path.join(ROOT, "tools", "fonts", "s3k_hud", "sonic-3-knuckles-hud-font.otf")
RENDER = 32   # render size
BRICK = 2     # pixels per brick at that size
FIRST, LAST = 32, 126
COLS = 16
ATLAS_W, ATLAS_H = 256, 128


def main():
    font = ImageFont.truetype(FONT, RENDER)
    ascent, descent = font.getmetrics()
    glyphs = {}
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        adv = round(font.getlength(ch) / BRICK)
        big = Image.new("1", (RENDER * 2, ascent + descent + 4), 0)
        d = ImageDraw.Draw(big)
        d.fontmode = "1"
        d.text((0, 0), ch, font=font, fill=1)
        small = Image.new("L", (big.width // BRICK, big.height // BRICK), 0)
        bp, sp = big.load(), small.load()
        for y in range(small.height):
            for x in range(small.width):
                sp[x, y] = 255 if bp[x * BRICK, y * BRICK] else 0
        glyphs[code] = (small, adv)

    # common vertical extent of all glyphs
    boxes = [g.getbbox() for g, _ in glyphs.values() if g.getbbox()]
    top = min(b[1] for b in boxes)
    bottom = max(b[3] for b in boxes)
    height = bottom - top
    cell_w = max(max((g.getbbox() or (0, 0, 0, 0))[2] for g, _ in glyphs.values()), max(a for _, a in glyphs.values()))
    rows = (LAST - FIRST + COLS) // COLS
    assert COLS * cell_w <= ATLAS_W and rows * height <= ATLAS_H, (cell_w, height)

    atlas = Image.new("RGBA", (ATLAS_W, ATLAS_H), (255, 255, 255, 0))
    widths = []
    for code in range(FIRST, LAST + 1):
        g, adv = glyphs[code]
        i = code - FIRST
        cx, cy = (i % COLS) * cell_w, (i // COLS) * height
        crop = g.crop((0, top, cell_w, bottom))
        white = Image.new("RGBA", crop.size, (255, 255, 255, 255))
        atlas.paste(white, (cx, cy), crop)
        widths.append(adv)

    gfx = os.path.join(ROOT, "gfx")
    atlas.save(os.path.join(gfx, "ui_font.png"))
    with open(os.path.join(gfx, "ui_font.t3s"), "w") as f:
        f.write("-f rgba5551 -z auto\nui_font.png\n")
    with open(os.path.join(ROOT, "source", "gen", "ui_font.h"), "w", newline="\n") as f:
        f.write("// Generated by tools/export_font.py - do not edit.\n#pragma once\n\n")
        f.write("// Sonic 3 & Knuckles HUD Font by chriswal1200 (FontStruct), CC BY-SA 3.0\n")
        f.write(f"#define UI_FONT_FIRST {FIRST}\n#define UI_FONT_LAST {LAST}\n#define UI_FONT_COLS {COLS}\n")
        f.write(f"#define UI_FONT_CELL_W {cell_w}\n#define UI_FONT_HEIGHT {height}\n")
        f.write(f"#define UI_FONT_ATLAS_W {ATLAS_W}\n#define UI_FONT_ATLAS_H {ATLAS_H}\n")
        f.write("static const unsigned char UI_FONT_ADVANCE[] = {")
        f.write(", ".join(str(w) for w in widths))
        f.write("};\n")
    print(f"ui_font: cell {cell_w}x{height}, {LAST - FIRST + 1} glyphs")


if __name__ == "__main__":
    main()
