#include "levels.h"

#include "gen/rooms.h"
#include "gen/sounds.h"

const LevelDef LEVELS[LEVEL_COUNT] = {
    { "Hide and Seek 2", ROOM_HIDEANDSEEK2, SND_MUS_HIDEANDSEEK2, SND_MUS_HIDEANDSEEK2_CHASE },
    { "Ravine Mist", ROOM_RAVINEMIST, SND_MUS_RAVIMEMIST, SND_MUS_RAVIMEMIST_CHASE },
    { "...", ROOM_DOTDOTDOT, SND_MUS_DOTDOTDOT, SND_MUS_DOTDOTDOT_CHASE },
    { "Desert Town", ROOM_DESERTTOWN, SND_MUS_DESERTTOWN, SND_MUS_DESERTTOWN_CHASE },
    { "You Can't Run", ROOM_YOUCANTRUN, SND_MUS_YOUCANTRUN, SND_MUS_YOUCANTRUN_CHASE },
    { "Limp City", ROOM_LIMPCITY, SND_MUS_LIMPCITY, SND_MUS_LIMPCITY_CHASE },
    { "Not Perfect", ROOM_NOTPERFECT, SND_MUS_NOTPERFECT, SND_MUS_NOTPERFECT_CHASE },
    { "Kind and Fair", ROOM_KINDANDFAIR, SND_MUS_KINDANDFAIR, SND_MUS_KINDANDFAIR_CHASE },
    { "Act 9", ROOM_ACT9, SND_MUS_ACT9, SND_MUS_ACT9_CHASE },
    { "Nasty Paradise", ROOM_NASTYPARADISE, SND_MUS_NASTYPARADISE, SND_MUS_NASTYPARADISE_CHASE },
    { "Priceless Freedom", ROOM_PRICELESSFREEDOM, SND_MUS_PRICELESSFREEDOM, SND_MUS_PRICELESSFREEDOM_CHASE },
    { "Volcano Valley", ROOM_VOLCANOVALLEY, SND_MUS_VOLCANOVALLEY, SND_MUS_VOLCANOVALLEY_CHASE },
    { "Green Hill", ROOM_GREENHILL, SND_MUS_HILL, SND_MUS_HILL_CHASE },
    { "Majin Forest", ROOM_MAJONGFOREST, SND_MUS_MAJINFOREST, SND_MUS_MAJINFOREST_CHASE },
    { "Hide and Seek", ROOM_ANGELISLAND, SND_MUS_ANGELISLAND, SND_MUS_ANGELISLAND_CHASE },
    { "Torture Cave", ROOM_TORTURECAVE, SND_MUS_TORTURECAVE, SND_MUS_TORTURECAVE_CHASE },
    { "Dark Tower", ROOM_DARTOWER, SND_MUS_DARKTOWER, SND_MUS_DARKTOWER_CHASE },
    { "Haunting Dream", ROOM_HAUNDREAM, SND_MUS_HAUNTDREAM, SND_MUS_HAUNTDREAM_CHASE },
    { "Wood Dream", ROOM_WEEDZONE, SND_MUS_WEEDZONE, SND_MUS_WEEDZONE_CHASE },
    { "Marijuna", ROOM_MARIJUNA, SND_MUS_MARIJUNA, SND_MUS_MARIJUNA_CHASE },
    { "Fart Zone", ROOM_FARTZONE, SND_MUS_FARTZONE, SND_MUS_FARTZONE_CHASE },
};
